version: '3.8'
services:
  flutter-web:
    image: www.stargaser.co.kr/flutter-test:1.4
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - registry
  api:
    image: www.stargaser.co.kr/api:0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # 여기서 호스트 이름은 db의 이름으로 해야함
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/sttest
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
  db:
    image: mariadb:10.6
    environment:
      - MARIADB_DATABASE=sttest
      - MARIADB_USER=root
      - MARIADB_PASSWORD=1234
      - MARIADB_ROOT_PASSWORD=1234
    labels:
      org.springframework.boot.service-connection: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: db
  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_SECRET: