// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.40.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Profile {
  final String name;
  final String email;
  final String phoneNumber;

  const Profile.raw({
    required this.name,
    required this.email,
    required this.phoneNumber,
  });

  static Profile fromJson({required Map<String, String> j}) =>
      RustLib.instance.api.crateApiModelsProfileProfileFromJson(j: j);

  static Profile mock() =>
      RustLib.instance.api.crateApiModelsProfileProfileMock();

  factory Profile(
          {required String name,
          required String email,
          required String phoneNumber}) =>
      RustLib.instance.api.crateApiModelsProfileProfileNew(
          name: name, email: email, phoneNumber: phoneNumber);

  Map<String, dynamic> toJson() =>
      RustLib.instance.api.crateApiModelsProfileProfileToJson(
        that: this,
      );

  @override
  int get hashCode => name.hashCode ^ email.hashCode ^ phoneNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          email == other.email &&
          phoneNumber == other.phoneNumber;
}
