// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.40.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/profile.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<Profile> phone(
        {required String name,
        required String email,
        required String phoneNumber}) =>
    RustLib.instance.api.crateApiSimplePhone(
        name: name, email: email, phoneNumber: phoneNumber);
